### ISSUE TITLE
MIME Type

### ISSUE THREAD

**Issue by cweiske** [ewilderj/doap#10]
It would be good to know what the official MIME type of DOAP files/URLs is.

I'd think `application/rdf+xml`, but `examples/redland-doap.rdf` says: 

> Though it is recommended DOAP files start with Project as the document
> element, they can be full fledged RDF files like this one is.

This would mean "normal" and "recommended" documents are no RDF and need a different MIME type.

**Comment by ewilderj** [comment]
Where DOAP is bare XML, you can serve it as `application/xml`
Where it is RDF, use an RDF media type as @elf-pavlik references.

I would consider registering a `prs.` media type per RFC6836—in which case, it would be `application/prs.doap+xml` and `application/prs.doap+json` as appropriate.

I'll leave this open while I evalute registering the `prs` media type.

**Comment by bblfish** [comment]
Your server does not seem to specify the mime type, as can be seen by the command. 

```bash
$ curl -i http://usefulinc.com/ns/doap | head
Date: Wed, 13 Apr 2022 04:07:16 GMT
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Sun, 04 Mar 2018 23:00:51 GMT
ETag: "d1eb-5669e2e49aec0"
Accept-Ranges: bytes
Content-Length: 53739

<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
```

**Comment by ewilderj** [comment]
This is fixed and will serve as `application/xml+rdf` for the canonical schema doc.

```
$ curl -i https://usefulinc.com/ns/doap | head
accept-ranges: bytes
age: 0
cache-control: public,max-age=0,must-revalidate
cache-status: "Netlify Edge"; fwd=miss
content-type: "application/rdf+xml"; charset=utf-8
date: Tue, 11 Jun 2024 00:02:54 GMT
etag: "bdb5cbb8590e957c732c6c5e98fe734b-ssl"
server: Netlify
strict-transport-security: max-age=31536000
```
