### ISSUE TITLE
Example of how to link from HTML pages

### ISSUE THREAD

**Issue by cweiske** [ewilderj/doap#11]
The wiki should contain an example of how to link to DOAP documents from a normal HTML page.

If DOAP documents are RDF, it would be:

```
<link rel="meta" title="DOAP" type="application/rdf+xml" href="path/to/doap"/>
```

What if the DOAP document is no RDF?

Is the DOAP title needed or optional?

**Comment by ewilderj** [comment]
If it's not RDF, we'd treat it per the MIME type decided by #10 — so I'll merge this bug with that.

Duplicate of #10
