### ISSUE TITLE
add examples in turtle and json-ld

### ISSUE THREAD

**Issue by elf-pavlik** [ewilderj/doap#13]
currently all examples us RDF-XML representation of RDF

many people find **turtle** more readable for human
also recent development of **json-ld** brings another representation which i would expect becoming very popular

**Comment by ewilderj** [comment]
@pmackay if you want to contribute one, please do! meanwhile i'll at least work though converting some more examples to turtle.

**Comment by danbri** [comment]
If you make a JSON-LD example people will then begin to lobby you to "do it properly" which means that there is a JSON-LD "context file" available at the URL used in "@ context" declarations. 

At schema.org we used the project homepage for that URL, and so eventually got it content negotiating HTML vs JSON-LD representations. I mention this as it bears upon question of which URL you use in @-context. Some but not all use the same URL as namespace URL.

**Comment by akuckartz** [comment]
:+1:

**Comment by ewilderj** [comment]
@danbri that brings me to the issue of asking you about HTML rendering of the FOAF schema and what you used. I'd like to render HTML docs if we're going to start content negotiation on the namespace URI

**Comment by danbri** [comment]
@ewilderj I originally wrote a horrid little Ruby script called specgen.rb, then it became .py, and there are a confusing range of forks and fixups of it floating around. I have no sense for the state of the art. If you want a solid Python library for RDF, rdflib seems to be it.
