### ISSUE TITLE
Source code location

### ISSUE THREAD

**Issue by evelynmitchell** [ewilderj/doap#21]
With the proliferation of sites like github and the like, it would be good to have a field which points to the home location of the code.

**Comment by ewilderj** [comment]
this is the function of doap:repository, e.g. for DOAP itself 

```<doap:repository rdf:resource="https://github.com/ewilderj/doap" />```

or more verbose

```
 <doap:repository>
   <doap:GitBranch rdf:about="https://github.com/ewilderj/doap" />
 </doap:repository>
```

(now I do agree GitBranch is poorly named, and I think DOAP can definitely do better at modeling Git semantics, therefore just sticking to `doap:repository` in the simple case is advised for now
