### ISSUE TITLE
SWI-Prolog packs

### ISSUE THREAD

**Issue by Anniepoo** [ewilderj/doap#26]
Just a heads up - over at https://github.com/swi-prolog  or http://swi-prolog.org there's talk going on of an ontology to describe prolog packs, and doap is prominently mentioned. Talk is happening on the mail list.

SWI-Prolog has a built in pack install function. If you want, say, the cowspeak pack you can install by querying 

?- pack_install(cowspeak).

we can already get various meta-data about the pack, but are thinking having it in something more rdf-y would be good.

**Comment by ewilderj** [comment]
Closing this out as a bit old now—sorry for being AWOL @Anniepoo when you posted it. If there's any more to know, please get in  touch!
