### ISSUE TITLE
Integrating DOAP in CodeMeta crosswalk table

### ISSUE THREAD

**Issue by moranegg** [ewilderj/doap#29]
​Hello,

I'm a research intern at [Software Heritage](https://www.softwareheritage.org/) which collects the source code of software projects from a variety of origins. The same source code can be collected from different origins, each providing potentially complementary or conflicting metadata describing the project of which this source code is part, and the people that take part in it.

As I was researching different software ontologies I discovered the [CodeMeta](https://github.com/codemeta/codemeta) ​initiative, where a  crosswalk table of metadata standards keeps different vocabularies.

I think it's important to integrate DOAP into the CodeMeta table and I'll be glad to do so,
but I would love your input on the translation between DOAP terms and CodeMeta terms:

| DOAP        | Description | CodeMeta         |
| ------------- |----- | ------------- |
| name    | The main name of the project, by which it is known publicly |     title |
| shortname|     A short name of the project, most often used for filenames    | - |
| homepage*    | URI of the project's homepage, associated only with this one project    | relatedLink |
| Old-homepage*    | URI of a project's past homepage, associated only with this one project    | relatedLink|
| created    Date|  when the project was created, in YYYY-MM-DD form    | dateCreated |
| description    | Plain text description of a project; several sentences |     description|
| shortdesc    | A short plain text description of a project; eight or nine words    | - |
| category    | A URI denoting a category assigned to the project |  tags|
| wiki    |  URI of a Wiki attached to this project | relatedLink
| bug-database    | URI of a bug tracker or e-mail address to report bugs on the project    | issueTracker |
| screenshots |     URI of a Web page with screenshots of the project |     relatedLink|
| mailing-list    | URI of a mailing list attached to this project    | relatedLink |
| programming-language    | Programming language this project is implemented in or intended for use with    | programmingLanguage |
| os    | Operating system the project is limited to (omit if the project is not OS-specific) |  operatingSystem  |
| license|     URI of a license through which the project software is available     | licenseId |
| download-page|     URI of the location where the project software can be downloaded     | downloadLink |
| download-mirror    | URI of a download mirror site      | -  |
| repository    | A doap:Repository describing a source code repository for the project |     codeRepository |
| release    | A doap:Version describing a current release of the project's software |     version |
| maintainer    | A foaf:Person describing the project maintainer or leader     | agents,role, isMaintainer |
| developer    | A foaf:Person describing a developer on the project | agents, role |
| documenter    | A foaf:Person describing a contributor of documentation to the project     | agents, role |
| translator    | A foaf:Person describing a contributor of translations to the project     | agents, role |
| helper     | A foaf:Person describing a contributor to the project not otherwise described by the other properties    | agents, role |
| | A URL for the instructions to create an executable version of the software from source code.| buildInstructions |
| | A URL for the continuous integration system| contIntegration |
| | Keywords associated with the software| controlledTerms|
| | | dateModified |
| | | datePublished |
| | The computer hardware and software required to run the software | depends |
| | A designation of the current state of the software in the development lifecycle | developmentStatus |
| | A calendar date specifying the end of a restricted access period | embargoDate |
| | An institution, organization or other entity that has provided monetary resources | funding |
| | | isAutomatedBuild |
| |  A logical value (true/false) indicating that an agent must be included in a citation of the software | agents.mustbeCited |
| | | isRightsHolder |
| | | publisher |
| | | readme |
| | | relatedPublications |
| | A universally unique character string associated with the software. | identifier |
| | | softwarePaperCitationIdentifiers |
| |  External software components that could enhance operation of or enable advanced functionality of the software package but are not strictly required | suggests |
| | The user identity that uploaded the software to an online repository | uploadedBy |
| | A URL for the software distribution in compressed form | zippedCode |

Also, I was wondering ​if​ you have statistics about the usage of DOAP ​o​n Github or in general?

Cheers,
Morane

**Comment by kjetilk** [comment]
The mapping sounds good to me!

The only thing I might add is that you could also look into using Dublic Core Terms for some of the properties that DOAP doesn't have, like dates.

**Comment by ewilderj** [comment]
Nice work, thanks for sharing it! I can't find any immediate comments, except to back up what @kjetilk said: your publisher, for instance, has a Dublin Core analog which could be used in DOAP descriptions.
