### ISSUE TITLE
Doap HTML

### ISSUE THREAD

**Issue by mongoponzo** [ewilderj/doap#32]
Is there any HTML version of the Doap ontology? The [official website](http://usefulinc.com/ns/doap#) only has the XML document which is very difficult to read.

**Comment by ewilderj** [comment]
Not yet. If you know of any RDF->HTML processors I'd be happy to automate that.

**Comment by kjetilk** [comment]
I suppose it depends on the environment it should run in. Back in the day, I used Drupal based Neologism, which was pretty good, but it isn't actively maintained. I suppose the what was used for FOAF might be usable?

**Comment by ewilderj** [comment]
It would be best if we could keep it all static, so that we could ship docs easily as part of the distribution. Time to hit up DanBri to find out what FOAF does I suppose!

**Comment by taurenshaman** [comment]
Here is a simple one:  
http://www.chuci.info/view/schema/97ac7e9e37694a238d7e3ca5b84efa38

**Comment by vemonet** [comment]
You can use the Python package Ontospy to generate a static HTML website to document any OWL ontology

https://pypi.org/project/ontospy/

You just need to provide the OWL ontology file to the ontospy command line, it will generate the HTML automatically in the folder you specified (e.g. in the `docs` folder)

Then you just need to publish to `docs` folder as GitHub Page.

It can be automated easily using GitHub Actions to generate and commit the docs at every change to the OWL file

**Comment by vemonet** [comment]
I generated documentation for the DOAP ontology using Ontospy and hosted it in GitHub Pages: https://vemonet.github.io/doap

```bash
pip install ontospy[FULL]
mkdir docs
ontospy gendocs -o docs https://raw.githubusercontent.com/vemonet/doap/master/schema/doap.rdf
```

Fork here: https://github.com/vemonet/doap/

All documentations file have been added to the `docs/` folder
