### ISSUE TITLE
docopt-0.6.2

### ISSUE THREAD

**Issue by ramsinghdayal** [ewilderj/doap#34]
#docopt-0.6.2 (https://pypi.python.org/pypi/docopt)

> > C:\Users\RD\Anaconda3\pkgs_rd\docopt-0.6.2r>pip install setup.py

Error: could not find the version that satisfies the requirement setup.py
Version: Python 3.6.1 !Anaconda 4.4.0 (32-bit) ! (default, date, time) [MSC v.1 900 32 bit (intel)] on win32

**Comment by ewilderj** [comment]
I think you've filed this on the wrong repository.
