### ISSUE TITLE
GDAL-2.2.0

### ISSUE THREAD

**Issue by ramsinghdayal** [ewilderj/doap#35]
#GDAL-2.2.0 (https://pypi.python.org/pypi/GDAL)

C:\Users\RD\Anaconda3\pkgs_rd\GDAL-2.2.0>pip install setup.py
Error: could not find the version that satisfies the requirement setup.py

Version: Python 3.6.1 !Anaconda 4.4.0 (32-bit) ! (default, date, time) [MSC v.1 900 32 bit (intel)] on win32

**Comment by ewilderj** [comment]
I think you've filed this on the wrong repository.
