### ISSUE TITLE
add way of saying project is OS-neutral  

### ISSUE THREAD

**Issue by ewilderj** [ewilderj/doap#4]
Java apps can be ran on any OS with a Java runtime. There's no way to specify this within the os property apart from using a string literal like "Any"

**Comment by Anniepoo** [comment]
Prolog!  Don't forget Prolog.  8cD  Prolog files are compile-at-load, and in SWI-Prolog (most commonly used version) you can make a .qlf file that's an executable that is (I think) cross platform.

**Comment by ewilderj** [comment]
I think I am tempted to deprecate "os" property over time in favor using the dependencies mechanisms we land on with #1. So, marking this issue for no further action.
