### ISSUE TITLE
Examples use GitRepository which isn’t defined in the schema

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#42]
viewer/doap.rdf and examples/doap-doap.rdf use `GitRepository`, while only `GitBranch` is defined in the schema.

A sensible solution would be #38.

**Comment by kjetilk** [comment]
Actually, since I already have deployed code that uses this, I suggest I just add it, OK?

**Comment by ewilderj** [comment]
GitBranch is definitely a weird mistake/thinko. I think adopting what's in the examples makes sense, if you want to prepare a patch

**Comment by kjetilk** [comment]
OK, but what if somebody is using GitBranch... Perhaps it is a good idea to keep it?

**Comment by ewilderj** [comment]
Yeah... I wonder if there are any conventions beyond documentation for
marking deprecation

**Comment by kjetilk** [comment]
I guess GitBranch might also be useful to someone. I hear that in big projects, people work a long time on a branch.

**Comment by ewilderj** [comment]
True, and I guess it needs to be a resource rather than a literal, as we
can use the Github URI eg.  https://github.com/ewilderj/doap/tree/master

**Comment by kjetilk** [comment]
I merged #55 yesterday, but it seems it hasn't shown up in the namespace document yet. Shouldn't that have happened automagically now, with https://github.com/ewilderj/doap/commit/95b0eb9985623daec67a2ef845f9111a14964701 ?

**Comment by ewilderj** [comment]
I have a race condition to resolve in the auto-deploy script, which I'll
fix soon. I just did a manual push, so it ought to be updated now.

**Comment by kjetilk** [comment]
OK, great, I'll close this, then. :-)
