### ISSUE TITLE
Wrong Content-Type for http://usefulinc.com/ns/doap

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#44]
The `Content-Type` header on this page should be `application/rdf+xml; charset=utf-8` to let user-agents render it properly.

**Comment by HughP** [comment]
Would this be the cause of various kinds of characters being rendered in the browser?
 for instance: for me on ubuntu 16.04/chrome at the url: http://usefulinc.com/ns/doap#
I see the following:

```	<dc:description xml:lang="cs">SlovnÃ­k Description of a Project (DOAP, Popis projektu), popsanÃ½ pouÅ¾itÃ­m W3C RDF Schema a Web Ontology Language.</dc:description>
	<dc:description xml:lang="pt">VocabulÃ¡rio de descriÃ§Ã£o de um Projeto (DOAP - Description of a Project), descrito no esquema (schema) W3C RDF e na Web Ontology Language.</dc:description>```

**Comment by kjetilk** [comment]
@HughP yes, that is most likely the reason.

**Comment by ewilderj** [comment]
This is finally fixed
