### ISSUE TITLE
Make http://usefulinc.com/ available in HTTPS, redirect to it, and add HSTS support

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#45]
This website is currently only available in plain text HTTP, making it susceptible to all kind of MitM attacks.

Here are all of the errors Firefox warns me about:
* The certificate is not trusted because the issuer certificate is unknown.
* The server might not be sending the appropriate intermediate certificates.
* An additional root certificate may need to be imported.
* The certificate is not valid for the name usefulinc.com.
* The certificate expired on November 16, 2016, 7:36 PM. The current time is August 20, 2017, 8:39 PM.

In addition, the HTTPS content points to an unrelated (?) root, with a default Apache2 page on Ubuntu and mailman archives.

A good solution would be to obtain a [Let’s Encrypt](https://letsencrypt.org/) certificate, automatise its renewal, and then configure Apache2 to only use the TLS version.

**Comment by ewilderj** [comment]
This has now been done.
