### ISSUE TITLE
Add instructions to build Redland.dll

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#48]
With a freshly-installed mono, running `make` in either viewer/ or validator/ results in a compilation error, saying that Redland.dll can’t be found.

My distribution (ArchLinux) provides a redland package but nothing that would hint at mono bindings.

**Comment by ewilderj** [comment]
These generators are very old code. Need help from somebody who is currently a Mono user.

**Comment by ewilderj** [comment]
Closing this down as WONTFIX.
