### ISSUE TITLE
language property doesn’t specify which version of ISO 639 it wants

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#49]
ISO 639 has three relevant parts, 639-1, 639-2 and 639-3, each of them defining a different set of languages.

For best interoperability it is important to specify which one should be used.

**Comment by HughP** [comment]
Is this property following the same assumptions as DCMI?

**Comment by akuckartz** [comment]
Please consider BCP 47:
https://tools.ietf.org/html/bcp47

**Comment by kjetilk** [comment]
I'm not sure what to do concretely with this. It might be a problem that older descriptions stops being compliant if we make a stricter definition, but can I suggest that some make a patch a PR that we can review?

**Comment by HughP** [comment]
+1 BCP 47

**Comment by HughP** [comment]
I am not sure why a a PR is required, I think what we are saying is that BCP47 is what is needed to be referenced instead of any of the ISO 639-3 standards. BCP47 will continue to be updated with the most relevant language standard, and then the DOAP standard does not need to formally be updated.

**Comment by kjetilk** [comment]
Yeah, it is just that it is better to have a concrete proposal to evaluate. I mean, if we are going to make changes, it is better that those who know better how the wording should be propose the exact changes, than those who do not really know what's at stake does it... :-)

But what you guys are saying is that a simple ```s/ISO/BCP47/``` will do?

**Comment by HughP** [comment]
```<rdf:Property rdf:about="http://usefulinc.com/ns/doap#language">
	<rdfs:isDefinedBy rdf:resource="http://usefulinc.com/ns/doap#" />
	<rdfs:label xml:lang="en">language</rdfs:label>
	<rdfs:label xml:lang="pt">idioma</rdfs:label>
	<rdfs:comment xml:lang="en">ISO language code a project has been translated into</rdfs:comment>
	<rdfs:comment xml:lang="pt">Código de idioma ISO do projeto para o qual foi traduzido</rdfs:comment>
	<rdfs:domain rdf:resource="http://usefulinc.com/ns/doap#Project" />
	<rdfs:range rdf:resource="http://www.w3.org/2000/01/rdf-schema#Literal" />
</rdf:Property>```

In the above code you state: "ISO language code a project has been translated into" this should be changed to just "BCP47 language code a project has been translated into" BCP 47 points to which ISO code to use at any given situation, what's more is that BCP 47 points to how locale tags should be generated, which is the real bit of info this property is trying to describe.

**Comment by kjetilk** [comment]
OK, Like PR #65 ?

Do we have consensus for doing that?

**Comment by Zash** [comment]
#65 was merged, can this issue be closed?

**Comment by kjetilk** [comment]
Yes, I think so.
