### ISSUE TITLE
Add a chat property

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#53]
Most projects have one or more chat venues, where users can reach the maintainers, either for support or to help with development, translation, etc.

It would be useful to be able to list the purpose(s) there.

**Comment by kjetilk** [comment]
Actually, this was the reason why I added support-forum and developer-forum, I needed a link to IRC channels :-) 

This links to [SIOC](http://sioc-project.org/), and can be used to link to all kinds of forums, chat included. 

In its simplest form, a single triple is enough, but you can add stuff from SIOC if you need to specify it further.

Does this sound OK?
