### ISSUE TITLE
We have no license

### ISSUE THREAD

**Issue by ewilderj** [ewilderj/doap#66]
This project was developed so long ago, it has no license.

I intend to apply the Apache 2 License to the work.

If you contributed, please indicate your assent in this issue:

@kjetilk @bufferoverflow @dachary  @bergus @irl @pypingou

**Comment by bergus** [comment]
I release any contributions I made to this project so far to the public domain. Do whatever you want with it! :-)

**Comment by pypingou** [comment]
Since I'm not entitled to public domain, consider my contributions under CC0 :-)

**Comment by irl** [comment]
+1 my contributions can be considered to be public domain. I'm not even sure they were large enough to be copyrightable anyway.

(@ewilderj please consider CC0 as a license instead though)

**Comment by dachary** [comment]
I agree to the license.

**Comment by kjetilk** [comment]
I agree to the Apache 2 License.

**Comment by ewilderj** [comment]
Thanks folks. Just waiting on @bufferoverflow and @Jonadabe 

(re license, I cannot use CC0 for reasons connected with my employer, but Apache 2 makes my ongoing involvement a lot easier. I am hopeful of new momentum due to overlap with some of my work priorities!)

**Comment by ewilderj** [comment]
Looks @bufferoverflow's changes are either rolled back, or ready to be removed (as the Github URL) changed again. I will go ahead with the licensing at the same time as removing his patch. Thanks, everybody!
