### ISSUE TITLE
Add additional maintainers?

### ISSUE THREAD

**Issue by hoijui** [ewilderj/doap#75]
Hello! :-)
first of all.. thank you for this, we would very much like to use it (in the Open Know-How ontology).
I am a bit concerned though, as.. @ewilderj , the maintainer, seems to be inactive here since quite some time. Would it maybe be possible to add additional maintainers, maybe @kjetilk , and one or two others?
The more people use this, the more it becomes a critical part of the infrastructure, and having one person alone at a choke-point, is a considerable risk-factor.
All the best and.. ride on! :-)

**Comment by kjetilk** [comment]
I'm certainly here to help. I think the main issue is to have some automation set up to publish to the namespace URI when changes are merged to main, but the possibility to have more maintainers is also nice.

**Comment by ewilderj** [comment]
Do we think Github actions could take care of the automation? Seems reasonable.

**Comment by hoijui** [comment]
Yep! :-)
Though, if nobody with rights is active, automation is of no use -> Having active maintainers is more important.

**Comment by kjetilk** [comment]
Yeah, I think a Github Action that runs on a merge to main to publish the NS document would be good. But indeed, we need to review and someone to merge to main when it is good to go.

**Comment by hoijui** [comment]
@ewilderj , would it be possible to add some maintainers?
I suggested @kjetilk because he seemed most active.
... maybe some more?

**Comment by hoijui** [comment]
ping!

**Comment by kjetilk** [comment]
Yeah, I guess more maintainers would be nice. I'm also not so active these days, so I don't know if I would be right person, but it would be nice to have automation around the things that are in use.

**Comment by ewilderj** [comment]
Hey everyone, I am active once again and will be doing a review of what needs updating and how we can future proof the vocabulary maintenance. SPDX building on DOAP means it needs to be around in perpetuity.

**Comment by ewilderj** [comment]
I have moved the hosting of usefulinc.com to Netlify, and it will rebuild ns/doap whenever there is a push to the DOAP repo. So basically, when a schema change is committed to `master` it will automatically be published.

Might need ~24hrs to fully complete DNS transition.

**Comment by ewilderj** [comment]
I am going to close the issue for now as  @kjetilk and I are paying a bit of attention right now. But I am interested in hearing from others who care about DOAP still. I will likely write a blog post about this. DOAP is now 20 years old!

**Comment by danbri** [comment]
SGTM

How much DOAP data is out there btw? Is it substantial? (where best to ask
chitchat questions like this? Xtech?:)

**Comment by ewilderj** [comment]
I don't know the answer to that completely, but there are some active users still.

I'm curious how much effort I should put into evolving this vocabulary, or rather just point people to SPDX for the future.

Nevertheless, doap:homepage is still used by the current SPDX specification so that alone is justification for keeping things neat and tidy.
