### ISSUE TITLE
Making a reference to DOAP, I need the date of original year of release ?

### ISSUE THREAD

**Issue by jonquet** [ewilderj/doap#76]
Especially for the repository, bug-database and mailing-list
This is for reference in MOD2.0: https://github.com/sifrproject/MOD-Ontology

**Comment by ewilderj** [comment]
Could you explain a bit more? (Sorry for the delay.) Were you wanting new schema properties, or information about the DOAP project?

**Comment by jonquet** [comment]
Hello. I need the date of the very first release of DOAP vocabulary.

**Comment by ewilderj** [comment]
I am trying to chase this down, it was definitely in 2003. The first published article I wrote about it was in 2004: where you can find reference here https://www.researchgate.net/publication/245844601_Decentralizing_Software_Project_Registries_with_DOAP

I will try and find the original text.

**Comment by ewilderj** [comment]
Original article for you

https://web.archive.org/web/20110216074224/http://www.ibm.com/developerworks/xml/library/x-osproj.html
