### ISSUE TITLE
Question (file extension)

### ISSUE THREAD

**Issue by sjehuda** [ewilderj/doap#77]
Hello,

What's the [file extension](https://github.com/ge0rg/easy-xmpp-invitation/issues/34) for DOAP?

**Comment by kjetilk** [comment]
DOAP is expressed in terms of [RDF](https://www.w3.org/RDF/) and RDF can be expressed in a number of different syntaxes. For historical reasons, it was originally expressed in XML, I guess you saw `.xml` and `.xrdf` back in the day. 

We weren't really big fans of XML though, so other syntaxes were developed. Most common today are [Turtle](https://www.w3.org/TR/turtle/) where `.ttl` is recommended, or [JSON-LD](https://json-ld.org/), where [`.jsonld`](https://www.w3.org/TR/json-ld/#iana-considerations) is recommended.

**Comment by sjehuda** [comment]
Thank you
