### ISSUE TITLE
http://usefulinc.com is down currently

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#78]
**Describe the bug**
The namespace http://usefulinc.com/ns/doap# used to also host the RDF description of DOAP, it is currently down and that is bothering people who rely on that.

**How to reproduce it**
Open http://usefulinc.com/ns/doap#.

**Expected behaviour**
The RDF file is available.

**Screenshots**
![wayland-screenshot-2023-06-14_08-57-01](https://github.com/ewilderj/doap/assets/7755816/ced502f7-458c-48ef-8e3e-447a8af01523)

**Environment**

- Falco version: No idea what that is.

- System info: Irrelevant.

- Cloud provider or hardware configuration:
- OS: Irrelevant.

- Kernel: Irrelevant.

- Installation method: Irrelevant.

**Additional context**
N/A

**Comment by ewilderj** [comment]
I have moved hosting to Netlify. Give 24 hours for DNS propagation and we shouldn't have downtime in future
