### ISSUE TITLE
http://usefulinc.com/ns/doap Server is not up

### ISSUE THREAD

**Issue by bipinprasad** [ewilderj/doap#79]
**Motivation**

**Feature**

**Alternatives**

**Additional context**

**Comment by kjetilk** [comment]
Yeah, it looks down from here too. @ewilderj is the only person who can fix that, I'm afraid.

**Comment by ewilderj** [comment]
I'll take a look. I'm still alive!

**Comment by ewilderj** [comment]
Looks like the IP address changed for the server. I will update the DNS.

**Comment by ewilderj** [comment]
DNS is changed, it should propagate within the hour.

**Comment by ewilderj** [comment]
Confirmed working again
